"use client";

import { useState, useEffect, Suspense } from "react";
import Image from "next/image";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import styles from "./page.module.css";

const TIMELINE_EVENTS = [
  { year: "2018", title: "The Inception", desc: "Jitendra Shah founded FIND Real Estate in Mumbai with a vision to streamline complex luxury residential acquisitions through cutting-edge digital visualization and absolute advisory integrity." },
  { year: "2020", title: "Cross-Border Expansion", desc: "Recognizing the massive demand from Indian investors for luxury Dubai properties, FIND established a premier branch in Dubai, uniting NRI wealth advisors with seasoned local brokers." },
  { year: "2023", title: "RERA & DLD Gold Member Status", desc: "Granted certified DLD Trustee partner credentials, enabling direct escrow account and instant unified Contract F/A/B registrations for international buyers." },
  { year: "2026", title: "Digital Platform Evolution", desc: "Unveiled our high-fidelity cross-border listing network, equipped with real-time reactive DLD fee estimators and direct certified advisor booking tools." }
];

const PRESS_ARTICLES = [
  {
    source: "Dubai Property Times",
    date: "March 2026",
    title: "How Jitendra Shah is Revolutionizing the Indo-Dubai Real Estate Corridor",
    snippet: "FIND Real Estate's cross-border advisor network has bridged over AED 450M in high-end residential sales this fiscal, establishing themselves as the premier advisory for NRI buyers in Dubai Hills and Palm Jumeirah."
  },
  {
    source: "The NRI Investor Journal",
    date: "January 2026",
    title: "Tax-Free ROI: The Ultimate Expat Magnet",
    snippet: "Founder Jitendra Shah breaks down the 100% tax-free rental returns and Capital Gains structure in Dubai, detailing why more family offices are shifting capital from Mumbai to prime freehold communities."
  },
  {
    source: "Global Real Estate Tech Review",
    date: "October 2025",
    title: "FIND Real Estate Introduces Zero-Friction Paperwork Integrations",
    snippet: "By integrating automated DLD escrow verification and RERA Contract tracing directly into their client portfolios, FIND has reduced standard property transaction settlement times by over 40%."
  }
];

const JOB_OPENINGS = [
  {
    title: "Luxury Property Consultant (Dubai Division)",
    location: "Downtown Dubai (Hybrid)",
    type: "Full-Time",
    commission: "Up to 65% Split",
    desc: "We are seeking a RERA-certified, highly ambitious broker to represent luxury listings across Palm Jumeirah and Dubai Hills Estate. Strong network and luxury sales experience are required.",
    requirements: ["Active RERA Broker License", "2+ years of Dubai Real Estate experience", "Exceptional negotiation and presentation skills"]
  },
  {
    title: "NRI Investment Specialist",
    location: "Mumbai Office / Dubai (Travel Required)",
    type: "Full-Time / Commission",
    commission: "Premium Split Scheme",
    desc: "Help Indian high-net-worth investors and family offices diversify capital into high-yield Dubai residential portfolios and navigate the 10-Year Golden Visa regulations.",
    requirements: ["Deep understanding of FEMA and NRI investment compliance", "Proven track record in luxury Indian or international real estate", "Strong networking with HNIs"]
  },
  {
    title: "Digital Client Relations Coordinator",
    location: "Remote / Mumbai Office",
    type: "Full-Time",
    commission: "Base + Performance Bonus",
    desc: "Manage incoming high-intent investor inquiries generated by our interactive valuation platform, matching clients with certified local brokers.",
    requirements: ["Flawless verbal and written English communication", "Familiarity with luxury real estate CRM tools", "Fast response and organizational skills"]
  }
];

function AboutContent() {
  const searchParams = useSearchParams();
  const [activeTab, setActiveTab] = useState("story");
  const [appliedJob, setAppliedJob] = useState(null); // track quick apply action
  const [applyName, setApplyName] = useState("");
  const [applyEmail, setApplyEmail] = useState("");
  const [applySuccess, setApplySuccess] = useState(false);

  useEffect(() => {
    const tabParam = searchParams.get("tab");
    if (tabParam && ["story", "press", "careers"].includes(tabParam)) {
      setActiveTab(tabParam);
    }
  }, [searchParams]);

  const handleApplySubmit = (e) => {
    e.preventDefault();
    setApplySuccess(true);
    setTimeout(() => {
      setAppliedJob(null);
      setApplySuccess(false);
      setApplyName("");
      setApplyEmail("");
    }, 3000);
  };

  return (
    <main className={styles.main}>
      {/* Sky Background */}
      <div className={styles.skyBg}>
        <Image
          src="/images/back.jpg"
          alt="Dubai Sky Background"
          fill
          priority
          className={styles.bgImage}
        />
      </div>

      <div className="container">
        {/* Page Header */}
        <div className={styles.header}>
          <h1 className={styles.title}>About <span className="em">FIND Real Estate</span></h1>
          <p className={styles.subtitle}>
            A premier international advisory bridging luxury real estate opportunities between India and Dubai. Founded by Jitendra Shah, built on integrity and digital innovation.
          </p>
        </div>

        {/* Tab Controls */}
        <div className={styles.tabsContainer}>
          <button
            className={`${styles.tabBtn} ${activeTab === "story" ? styles.activeTab : ""}`}
            onClick={() => setActiveTab("story")}
          >
            Our Story & Founder
          </button>
          <button
            className={`${styles.tabBtn} ${activeTab === "press" ? styles.activeTab : ""}`}
            onClick={() => setActiveTab("press")}
          >
            Press & Media
          </button>
          <button
            className={`${styles.tabBtn} ${activeTab === "careers" ? styles.activeTab : ""}`}
            onClick={() => setActiveTab("careers")}
          >
            Careers & Commission
          </button>
        </div>

        {/* Tab Content Panels */}
        <div className={`${styles.contentCard} glass`}>
          {activeTab === "story" && (
            <div className={styles.storyPanel}>
              <div className={styles.storyIntro}>
                <div className={styles.introText}>
                  <h2>Bridging Borders, Securing Assets</h2>
                  <p className={styles.panelDesc}>
                    FIND Real Estate was established with a singular, powerful mission: to replace traditional real estate friction with complete transparency, absolute advisory integrity, and modern data-driven intelligence.
                  </p>
                  <p className={styles.storyParagraph}>
                    Under the leadership of our founder, **Jitendra Shah**, we have evolved from a premier boutique Mumbai residential agency into a dynamic, cross-border real estate powerhouse. Today, we specialize in helping Indian HNIs, corporate executives, and international expats successfully acquire, manage, and scale high-yield residential and commercial portfolios in **Dubai's tax-free freehold zones**.
                  </p>
                </div>

                {/* Founder Profile Card */}
                <div className={styles.founderCard}>
                  <div className={styles.founderLogoContainer}>
                    <Image
                      src="/images/js-logo.png"
                      alt="JS Brand Logo"
                      width={60}
                      height={60}
                      className={styles.founderLogo}
                    />
                  </div>
                  <h3>Jitendra Shah</h3>
                  <span className={styles.founderTitle}>Founder & Managing Director</span>
                  <p className={styles.founderBio}>
                    "Real estate is not just about transactions; it's about alignment. Our goal is to empower buyers with 100% verified regulatory knowledge, real-time cost transparency, and premier local advisors so their wealth transitions flawlessly."
                  </p>
                  <div className={styles.founderContact}>
                    <span><strong>Cell: </strong> +91 8451054341</span>
                    <span><strong>Email: </strong> shah.jeetu08@gmail.com</span>
                  </div>
                  <Link href="/about/contact" className="btn-round btn-round-primary" style={{ width: '100%', textAlign: 'center', marginTop: '1.6rem' }}>
                    Connect with Jitendra
                  </Link>
                </div>
              </div>

              {/* Timeline */}
              <div className={styles.timelineSection}>
                <h3>Our Growth Journey</h3>
                <div className={styles.timelineGrid}>
                  {TIMELINE_EVENTS.map((event, idx) => (
                    <div key={idx} className={styles.timelineItem}>
                      <div className={styles.timelineYear}>{event.year}</div>
                      <div className={styles.timelineCard}>
                        <h4>{event.title}</h4>
                        <p>{event.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {activeTab === "press" && (
            <div className={styles.pressPanel}>
              <h2>FIND Real Estate in the Press</h2>
              <p className={styles.panelDesc}>Read our latest features, market analyses, and structural technology highlights covered by leading global property media.</p>

              <div className={styles.pressGrid}>
                {PRESS_ARTICLES.map((article, idx) => (
                  <div key={idx} className={styles.pressCard}>
                    <div className={styles.pressMeta}>
                      <span className={styles.pressSource}>{article.source}</span>
                      <span className={styles.pressDate}>{article.date}</span>
                    </div>
                    <h3>{article.title}</h3>
                    <p className={styles.pressSnippet}>"{article.snippet}"</p>
                  </div>
                ))}
              </div>

              <div className={styles.mediaInquiries}>
                <h3>For Media & PR Inquiries</h3>
                <p>Are you a journalist looking for real-time data regarding the Indo-Dubai real estate corridor or tax-free HNI investment flows? Contact our press division directly.</p>
                <a href="mailto:shah.jeetu08@gmail.com" className="btn-round btn-round-primary">
                  Email Press Division
                </a>
              </div>
            </div>
          )}

          {activeTab === "careers" && (
            <div className={styles.careersPanel}>
              <div className={styles.careersIntro}>
                <h2>Join the FIND Advisor Network</h2>
                <p className={styles.panelDesc}>
                  We believe that elite agents deserve elite technology, uncompromised commission splits, and complete operational freedom. That's why we built FIND.
                </p>
                
                <div className={styles.benefitsGrid}>
                  <div className={styles.benefitCard}>
                    <h4>Industry-Leading Splits</h4>
                    <p>Earn up to 65% of your commission bookings, paid immediately upon transaction DLD clearance. No hidden royalty fees.</p>
                  </div>
                  <div className={styles.benefitCard}>
                    <h4>Premium Digital Pipeline</h4>
                    <p>Receive high-intent, pre-qualified buyer inquiries looking specifically for premium off-plan or ready residences.</p>
                  </div>
                  <div className={styles.benefitCard}>
                    <h4>Cross-Border Support</h4>
                    <p>Capitalize on our dual presence in Mumbai and Dubai, effortlessly closing deals for cross-border expat clients.</p>
                  </div>
                </div>
              </div>

              <h3>Active Openings</h3>
              <div className={styles.jobsList}>
                {JOB_OPENINGS.map((job, idx) => (
                  <div key={idx} className={styles.jobCard}>
                    <div className={styles.jobHeader}>
                      <div>
                        <h4>{job.title}</h4>
                        <span className={styles.jobLocation}>{job.location}</span>
                      </div>
                      <span className={styles.jobCommission}>{job.commission}</span>
                    </div>
                    <p className={styles.jobDesc}>{job.desc}</p>
                    <div className={styles.jobRequirements}>
                      <strong>Key Requirements:</strong>
                      <ul>
                        {job.requirements.map((req, i) => (
                          <li key={i}>{req}</li>
                        ))}
                      </ul>
                    </div>
                    <button
                      className="btn-round btn-round-primary"
                      onClick={() => setAppliedJob(job)}
                    >
                      Quick Apply
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Quick Apply Modal */}
      {appliedJob && (
        <div className={styles.modalOverlay}>
          <div className={`${styles.modalCard} glass`}>
            <button className={styles.closeModal} onClick={() => setAppliedJob(null)}>×</button>
            
            {!applySuccess ? (
              <form className={styles.modalForm} onSubmit={handleApplySubmit}>
                <h3>Apply for Open Position</h3>
                <span className={styles.modalJobTitle}>{appliedJob.title}</span>
                <p className={styles.modalJobSub}>{appliedJob.location} • {appliedJob.commission}</p>

                <div className={styles.formGroup}>
                  <label htmlFor="modal-name">Full Name</label>
                  <input
                    type="text"
                    id="modal-name"
                    value={applyName}
                    onChange={(e) => setApplyName(e.target.value)}
                    placeholder="Your Name"
                    required
                  />
                </div>

                <div className={styles.formGroup}>
                  <label htmlFor="modal-email">Email Address</label>
                  <input
                    type="email"
                    id="modal-email"
                    value={applyEmail}
                    onChange={(e) => setApplyEmail(e.target.value)}
                    placeholder="name@email.com"
                    required
                  />
                </div>

                <div className={styles.formGroup}>
                  <label htmlFor="modal-notes">Short Pitch / Portfolio Links</label>
                  <textarea
                    id="modal-notes"
                    placeholder="Why are you a great fit for FIND Real Estate?"
                    rows="3"
                  ></textarea>
                </div>

                <button type="submit" className="btn-round btn-round-primary" style={{ width: '100%' }}>
                  Submit Application
                </button>
              </form>
            ) : (
              <div className={styles.modalSuccess}>
                <div className={styles.successIcon}>✓</div>
                <h3>Application Submitted!</h3>
                <p>Thank you, {applyName}. Jitendra Shah and the FIND management team will review your credentials and get back to you shortly.</p>
              </div>
            )}
          </div>
        </div>
      )}
    </main>
  );
}

export default function AboutPage() {
  return (
    <Suspense fallback={
      <main className={styles.main} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', color: '#fff' }}>
        <div style={{ fontSize: '1.2rem', opacity: 0.8 }}>Loading About FIND Real Estate...</div>
      </main>
    }>
      <AboutContent />
    </Suspense>
  );
}
